import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { LandingFooter } from "./landing-footer";
import { LandingNavbar } from "./landing-navbar";
import { getDictionary, type Locale } from "@/lib/i18n";
import { getModuleBySlug } from "@/lib/modules";

const moduleLinks = ["suscripciones", "punto-de-venta", "rh-y-nomina", "finanzas"] as const;
export function OperationsPage({ locale }: { locale: Locale }) {
  const dictionary = getDictionary(locale);
  const copy = dictionary.landing.operationsPage;
  return <main className="landing-palette min-h-screen bg-[var(--landing-bg)] text-[var(--landing-text)]"><LandingNavbar locale={locale} />
    <section className="relative overflow-hidden border-b border-[color:var(--landing-border)] bg-[var(--landing-hero-bg)]"><div className="landing-dot-grid absolute inset-0" /><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--landing-accent-strong)]">{copy.eyebrow}</p><h1 className="mt-4 max-w-5xl text-5xl font-black uppercase leading-none sm:text-7xl">{copy.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--landing-copy)]">{copy.description}</p></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--landing-accent-strong)]">{copy.pillarsEyebrow}</p><h2 className="mt-3 text-4xl font-black uppercase">{copy.pillarsTitle}</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{copy.pillars.map((item) => <article key={item.title} className="border border-[color:var(--landing-border)] bg-[var(--landing-panel)] p-6"><CheckCircle2 className="h-5 w-5 text-[var(--landing-accent-strong)]" /><h3 className="mt-4 text-xl font-black">{item.title}</h3><p className="mt-3 text-[var(--landing-copy)]">{item.description}</p></article>)}</div></section>
    <section className="border-y border-[color:var(--landing-border)] bg-[var(--landing-panel-muted)]"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--landing-accent-strong)]">{copy.flowEyebrow}</p><h2 className="mt-3 text-4xl font-black uppercase">{copy.flowTitle}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{copy.steps.map((item, index) => <article key={item.title} className="border border-[color:var(--landing-border)] bg-[var(--landing-panel)] p-6"><span className="text-3xl font-black text-[var(--landing-accent-strong)]">0{index + 1}</span><h3 className="mt-5 text-xl font-black">{item.title}</h3><p className="mt-3 text-[var(--landing-copy)]">{item.description}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-xs font-black uppercase tracking-[.24em] text-[var(--landing-accent-strong)]">{copy.modulesEyebrow}</p><h2 className="mt-3 text-4xl font-black uppercase">{copy.modulesTitle}</h2><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{moduleLinks.map((slug) => { const item = getModuleBySlug(slug, locale)!; return <Link key={slug} href={`/${locale}/modules/${slug}`} className="group border border-[color:var(--landing-border)] bg-[var(--landing-panel)] p-5"><strong className="block text-lg">{item.label}</strong><span className="mt-4 inline-flex items-center gap-2 text-xs font-black uppercase text-[var(--landing-accent-strong)]">{copy.moduleAction}<ArrowRight className="h-4 w-4" /></span></Link>; })}</div></section><LandingFooter locale={locale} /></main>;
}
